// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx0kMg2zLglLGNHEJxkFZxCuACgPoic9g',
    appId: '1:848606971909:web:4f97eb04b6a2ae962db46c',
    messagingSenderId: '848606971909',
    projectId: 'gyro-bbcfe',
    authDomain: 'gyro-bbcfe.firebaseapp.com',
    databaseURL: 'https://gyro-bbcfe-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gyro-bbcfe.appspot.com',
    measurementId: 'G-2CBF2Z38VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeQq6bAwl1yJ89UyzdDzMRRgyO3A-hLVg',
    appId: '1:848606971909:android:96b06847c8bed6ac2db46c',
    messagingSenderId: '848606971909',
    projectId: 'gyro-bbcfe',
    databaseURL: 'https://gyro-bbcfe-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gyro-bbcfe.appspot.com',
  );
}
